const Discord = require('discord.js');

module.exports = {
  join: (user) => new Discord.RichEmbed()
    .setTitle(':cucumber: Nouveau membre')
    .setColor(0x39d600)
    .setDescription(user.tag + " (" + user.id + ") est arrivé !"),
  left: (user) => new Discord.RichEmbed()
    .setTitle('Membre parti')
    .setDescription(user.tag + " (" + user.id + ") est parti !"),
  welcome: (user) => new Discord.RichEmbed()
    .setTitle("DraftMan.fr - WebDesigner", "https://www.draftman.fr")
    .setDescription("Bienvenue à toi " + user.username + " sur le serveur Discord de DraftMan\nC'est un discord qui vise à rassembler ses connaissances et les personnes qui lui sont cher !\nSi tu es là c'est soit qu'il t'as invité par ce qu'il te considère comme une personne qu'il aprécie soit tu es un client ou une personne interessé par ce qu'il fait !\nSi tu es un client je t'encourage à faire la commande `/commande` pour qu'il puisse prendre contact avec toi plus facilement !")
    .setColor(0xcd6e57)
    .setURL("https://www.draftman.fr")
    .setFooter("DraftMan | Développeur FrontEnd & Graphiste", "https://www.draftman.fr/images/avatar.jpg")
    .setThumbnail("https://www.draftman.fr/images/avatar.jpg"),
  infos: () => new Discord.RichEmbed()
    .setTitle("Informations")
    .setDescription("Voici quelques informations")
    .setColor(0xcd6e57)
    .setFooter("DraftMan | Développeur FrontEnd & Graphiste", "https://www.draftman.fr/images/avatar.jpg")
    .addField("Membres", message.guild.memberCount, true)
    .addField("Membres Connectés", connect, true)
    .addField("Lib du bot", "[discord.js](https://discord.js.org)", true)
    .addField("Website", "[draftman.fr](https://www.draftman.fr/)", true)
    .addField("Discord", "[draftman.fr/discord](https://www.draftman.fr/discord)", true)
    .addField("Twitter", "[draftman.fr/twitter](https://twitter.com/DraftMan_Dev)", true)
    .addField("Développeur", "DraftMan#6284", true),
  doc: (name,doc) => new Discord.RichEmbed()
    .setTitle(`Documentation de ${name}`)
    .setDescription(`${doc.join("\n")}`)
    .setColor(0xcd6e57)
    .setTimestamp(new Date())
    .setFooter("DraftMan | Développeur FrontEnd & Graphiste", "https://www.draftman.fr/images/favicon.png"),
  help: () => new Discord.RichEmbed()
    .setTitle("Liste des commandes du DraftBot")
    .setDescription("Voici la liste de toutes les commandes qui te permettra de m'utiliser !")
    .setColor(0xcd6e57)
    .setFooter("DraftMan | Développeur FrontEnd & Graphiste", "https://www.draftman.fr/images/avatar.jpg")
    .setThumbnail("https://www.draftman.fr/images/avatar.jpg")
    .addField("/say <titre§message> | <titre§message§url>", "Permet de faire dire quelque chose au bot sous forme d'embed.")
    .addField("/commande", "Permet de passer directement en contact avec DraftMan pour une commande.")
    .addField("/google <question>", "Permet d'envoyer un lien lmgtfy.")
    .addField("/quote <id>", "Permet de répéter un message en embed.")
    .addField("/infos", "Permet d'avoir des informations sur le discord.")
    .addField("/doc <nom>", "Permet d'afficher une documentation.")
    .addField("/fortnite <nom>", "Permet d'afficher les statistiques d'un joueur.")
    .addField("/ping", "Permet d'afficher votre ping.")
    .addField("/clear <nombre>", "Permet de supprimer des messages en masse")
    .addField("/help", "Permet d'afficher l'aide")
    .addField("/level", "Permet d'afficher notre niveau sur le serveur **(SOON)**")
    .addField("▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬", "Musique")
    .addField("/play <url>|<recherche>", "Lancer une musique/playlist de Youtube")
    .addField("/musique", "Afficher une musique en cours")
    .addField("/skip", "Passer une musique en cours")
    .addField("/pause", "Mettre en pause la musique")
    .addField("/resume", "Relancer la musique")
    .addField("/queue", "Afficher la liste des musiques en attente")
    .addField("/purge", "Vider la liste des musiques en attente")
    .addField("/volume", "Ajuster le volume")
    .addField("/stop", "Arrêter la musique et vider la liste d'attente")
    .addField("/join", "Faire se connecter le bot au salon vocal")
    .addField("/leave", "Faire se déconnecter le bot au salon vocal")
    .addField("▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬", "D'autres commandes arriverons suivant les différentes updates."),
    /*.addField("/kick <membre>", "Exclure un membre du discord")
    .addField("/ban <membre>", "Bannir un membre du discord")*/
  songEmbed: (song) => new Discord.RichEmbed()
    .addField(":notes: En cours",`[${song.title}](${song.url}) ajouté par **${song.author}**`)
    .setThumbnail(`${song.thumbnail}`)
    .setTimestamp(new Date())
    .setFooter("DraftMan | Développeur FrontEnd & Graphiste", "https://www.draftman.fr/images/avatar.jpg"),
}
